const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.join(__dirname, 'icons');
const OUTPUT_FILE = path.join(__dirname, 'icons.js');

const icons = {};

fs.readdirSync(ICONS_DIR).forEach(file => {
  if (file.endsWith('.svg')) {
    const name = path.basename(file, '.svg');
    const content = fs.readFileSync(path.join(ICONS_DIR, file), 'utf8').trim();
    icons[name] = content.replace(/\n/g, '').replace(/"/g, '\\"');
  }
});

const output = `
// Auto-generated by build-icons.js
const FlowerIcons = {
${Object.entries(icons).map(([name, svg]) => `  "${name}": "${svg}"`).join(',\n')}
};

function getFlowerIcon(name) {
  return FlowerIcons[name] || '';
}

function insertFlowerIcon(name, element) {
  if (FlowerIcons[name]) {
    element.innerHTML = FlowerIcons[name];
  }
}

if (typeof module !== 'undefined') {
  module.exports = { FlowerIcons, getFlowerIcon, insertFlowerIcon };
}
`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log('icons.js generated!');
